-- PIZZA SALES PROJECT - BASIC SQL QUERIES--

-- Q1) Retrieve the total number of orders placed.
SELECT 
    COUNT(*) AS TOTAL_ORDERS_PLACED
FROM
    ORDERS;

-- Q2) Calculate the total revenue generated from pizza sales.
SELECT 
    ROUND(SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE),
            0) AS TOTAL_SALES
FROM
    ORDER_DETAILS
        JOIN
    PIZZAS ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID;
    
-- Q3) Identify the highest-priced pizza.
SELECT 
    PIZZA_TYPES.NAME AS PIZZA_NAME, PIZZAS.PRICE AS PRICE
FROM
    PIZZA_TYPES
        JOIN
    PIZZAS ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
ORDER BY PIZZAS.PRICE DESC
LIMIT 1;

-- Q4) Identify the most common pizza size ordered.
SELECT 
    PIZZAS.SIZE AS COMMON_SIZE,
    COUNT(ORDER_DETAILS.ORDER_DETAILS_ID) AS ORDER_COUNT
FROM
    PIZZAS
        JOIN
    ORDER_DETAILS ON PIZZAS.PIZZA_ID = ORDER_DETAILS.PIZZA_ID
GROUP BY COMMON_SIZE
ORDER BY ORDER_COUNT DESC LIMIT 1;

-- Q5) List the top 5 most ordered pizza types along with their quantities.
SELECT 
    PIZZA_TYPES.NAME AS MOST_ORDERED_PIZZA,
    SUM(ORDER_DETAILS.QUANTITY) AS QUANTITY
FROM
    PIZZA_TYPES
        JOIN
    PIZZAS ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
        JOIN
    ORDER_DETAILS ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
GROUP BY NAME
ORDER BY QUANTITY DESC
LIMIT 5;